### ISSUE TITLE
Double feedback loop for controlled variables

### ISSUE THREAD

**Issue by malikolivier** [aflak-vis/aflak#2]
In this issue, I refer as "controlled variables", all the variables in the node graph whose value is controlled from the visualization window.
 
Such variable cannot be edited from the node graph. It would be great if they could be edited from the node graph  as well, updating at the same time the representation of the variable within the visualization window.

**Comment by malikolivier** [comment]
@kazuyakusastro I implemented double feedback loop for controlled variables.
From now on, if you change the value of a variable within the node editor, the plot view will be updated accordingly.

**Comment by kazuyakusastro** [comment]
Thanks! I confirmed it with my PC.
