### ISSUE TITLE
Use nearest interpolation on displaying image data

### ISSUE THREAD

**Issue by malikolivier** [aflak-vis/aflak#23]
Current textures are smoothed on display. We shall disable that.

**Comment by malikolivier** [comment]
@kazuyakusastro こんな感じでいかがですか？

![image](https://user-images.githubusercontent.com/14120117/49059102-8eacef80-f24a-11e8-9cfb-04fd7edf1e53.png)

**Comment by kazuyakusastro** [comment]
とても良いと思います。
