### ISSUE TITLE
Deserialization Error when expand Windows' Path

### ISSUE THREAD

**Issue by dabokun** [aflak-vis/aflak#25]
Windowsにおける起動時のDeserialization Errorについて調査しました。
現在のWindows環境では、templateにおけるpathが例えば次のように展開されているようです。
```
((1), (
    t: Constant(Path("C:\cygwin64\home\kstrb\aflak-vis\aflak\src\file.fits")),
    input_defaults: [
    ],
)),
```
実際、このようにtemplateを記述してpathを使ったフォーマットを無くすと同じエラーが出ました。

この時"C:\cyg.."の"\c"の部分が、https://github.com/ron-rs/ron/blob/master/src/parse.rs の574行目に引っかかり、Unknown escape characterだと認識されていると予想されます。

Travis CIのテストでエラーが出なかったのは、このようなバックスラッシュが含まれていなかったからだと思われます。

**Comment by malikolivier** [comment]
Windows的なエラーでなく、単にPathに`\`が入ればそういうエラーが発生しますね！
こちらでこのバグを再現する単位テストを作りました。

修正してみます！
