### ISSUE TITLE
Case study: Visualizing the absorption spectral line of Natrium

### ISSUE THREAD

**Issue by dabokun** [aflak-vis/aflak#5]
銀河の連続光からNaの吸収線をわかりやすく見えるようにする。
→吸収線がある画像とない画像(少しズラす)の差分or割り算を行う。他の輝線を目印にしてアタリをつけて探す。
方法としては…
mangaデータからデータをとる→波長方向の赤方偏移の補正(赤方偏移のデータもヘッダーにある)→ある中心波長と幅を指定→その幅に入っている光全部足して画像をつくる(輝線を挟んだ範囲で画像をつくる)

したがって，
①fitsのメタデータを読む(赤方偏移等)(フォーマットに注意)
②スペクトルに対し，ある方法で範囲を指定(中心波長と幅，または最大値最小値)
③指定範囲の画像を足し合わせる
の実装が必要になると考えられる

**Comment by malikolivier** [comment]
@kazuyakusastro 必要でしたら、コメントなどを加えて頂ければ助かります。

**Comment by kazuyakusastro** [comment]
issueの立ち上げ、ありがとうございます。
コメントを作ったら長文になってしまいました。

まず、用語の定義をします。
(今後のことを考えると、wikiか何かにまとめて書いておいた方がいいかと考えています。)
- Å (オングストローム; angstrom): 長さの単位。1 Å = 0.1 nm = 10^-10 m。A (アルファベットのエー) で代用することが多い。
- on-band: 注目する吸収線 (または輝線) を含む波長帯。今回の研究テーマの場合は、Na D線の5890 Aと5896 A付近の波長帯で、例えば5885-5901 Aなど。
- off-band: on-bandの前後の波長帯。今回の研究では5870-5880 Aと5905-5920 Aなど。on-bandに吸収 (または放射) があるか判定するための基準となる。
- 等価幅 (equivalent width): 吸収線 (または輝線) の強さを表す物理量。単位は長さの次元を持ち、多くの場合はA (オングストローム)。今回の研究では各場所の等価幅を表すマップ (等価幅マップ) を作ることが目標となる。

続いて、各処理の詳細についてです。

1. mangaデータからデータをとる
これはSDSS/MaNGAのウェブページからデータをダウンロードすることも含むのでしょうか？
ダウンロードページについて、下記に詳しい説明があります。
https://www.sdss.org/dr14/manga/manga-data/data-access/
今回のケースでは、URLは
https://data.sdss.org/sas/dr14/manga/spectro/redux/v2_1_2/[PLATE]/stack/manga-[PLATE]-[IFUDESIGN]-LINCUBE.fits.gz
になります。
PLATEの一覧は
https://data.sdss.org/sas/dr14/manga/spectro/redux/v2_1_2/
にある数字のディレクトリになります。
Data Release (DR) が進むと、「dr14」の数字の部分が変化していくと思います。

2. 波長方向の赤方偏移の補正
fitsヘッダーに赤方偏移の情報があると思っていましたが、ありませんでした。
今回のケースでは赤方偏移は0から0.15の間にあることが分かっており、補正なしでもそこまで困ることはありません。
D線以外で赤方偏移を決めて補正ができると、(他のサイエンスケースを含めて) 楽になります。

3. ある中心波長と幅を指定
4. その幅に入っている光全部足して画像をつくる
3と4の手順をon-band、off-band x 2の計3bandで行います。
手順3を中心波長と幅で指定するか、最大値と最小値で指定するかは悩みどころで、理想的にはどちらでもできると嬉しいです。
手順4で、後の手順を考えると波長範囲の平均fluxの方が楽かも知れません。
足した後に波長範囲で割るだけですから、大した手間ではないと思います。

5. on-band中心波長における、off-bandの線型結合画像を作る
off-band画像2枚から波長方向に内挿して、on-band中心波長における画像を作ります。
すでにあるnodeの linear_composition_2d に接続して、2画像の比率を入力すればできます。

6. 等価幅マップ作成
あとは画像の四則演算です。
(等価幅マップ) = (off-bandの線型結合マップ - on-bandマップ) x (on-bandの波長範囲) / (off-bandの線型結合マップ)
これで等価幅マップが完成です。

最後に、nodeの粒度についてです。
等価幅マップ作成は一般的によく使われる解析であり、手順3-6をひとまとめにして、面分光データと波長範囲を入力、等価幅マップを出力にしてはどうかと考えています。
等価幅マップ作成node内でどういう計算をしているか気になる人のために、nodeを一時的にunpackして中身の数字を見たり途中経過画像を出力できるようになると、確認がしやすくなります。

手順3-4のある波長範囲を足し上げた画像作成、さらには画像やスペクトルの四則演算は多くの処理に使われるので、nodeとして用意してあると助かります。
nodeの種類がどんどん増えていく可能性があるため、nodeをどのようにして整理整頓して並べるかが重要になりそうです。 (こうなると画像編集ソフトに近いかも。)
また、等価幅マップ作成nodeとは逆に、自分で四則演算などを組み合わせてnode化したい (自作関数) という要望があるかもしれません。
等価幅マップ作成nodeと自作関数nodeを同じ扱いで分類できるのでは、と思います。

以上です。
長文となってしまいましたが、よろしくお願いします。

**Comment by dabokun** [comment]
わかりやすい説明ありがとうございます。
自信はないのですが、一応、必要そうなノード(平均fluxの計算と等価幅マップの計算)を作成し以下のような結果を得ました。

波長範囲は上記で教えていただいたものを計算して利用しています(赤方偏移は0.04程度(Hαで266Å程度のずれ)と計算できたのでその値を使用しています)。

値の振れ幅が大きく、(off-bandの線型結合マップ - on-bandマップ) / (off-bandの線型結合マップ)が-1未満または1より大きいものは除外(0に書き換え)しているのですが大丈夫なのでしょうか。
![image](https://user-images.githubusercontent.com/37533832/46541839-010eec80-c8f8-11e8-9a50-bc667d02415d.png)

他のfitsでも試してみようと思っていますが、MANGAの中で既に等価幅マップの結果がわかっているような例があると正当性を検証しやすいと思います。そのようなものはありますでしょうか？(例えば、ある論文で、あるfitsのこの吸収線領域における等価幅マップ結果が載っている、のようなもの)

**Comment by kazuyakusastro** [comment]
早速ありがとうございます。
今は自宅にいて、詳細までは調べられませんが、簡単に分かるところのみ回答し、詳細は明日以降に回答します。

> 波長範囲は上記で教えていただいたものを計算して利用しています(赤方偏移は0.04程度(Hαで266Å程度のずれ)と計算できたのでその値を使用しています)。

計算プロセスは概ね正しいように見えます。
Hαのすぐ近くに別の輝線があって、波長範囲はon/offともに不適切となっていそうです。
Hαの場合の適切な範囲は後日お知らせします。

> 値の振れ幅が大きく、(off-bandの線型結合マップ - on-bandマップ) / (off-bandの線型結合マップ)が-1未満または1より大きいものは除外(0に書き換え)しているのですが大丈夫なのでしょうか。

(off-bandの線型結合マップ) の値が小さい場所では、値の振れ幅がとても大きくなります。
上記計算結果はノイズがあるとどんな値にもなり得るので、0に置き換えるのはいけません。
(この天体の中心部では、ノイズなしでも-1以下になっていると思います。)

(off-bandの線型結合マップ) の値がある値より小さい場所では、上記計算結果を0に置き換える (maskする) のはよく行う処理です。
(off-bandの線型結合マップ) の値以外でmaskすることもあるので、maskマップ (offマップである値より小さいと0、それ以上で1のマップ) を作り、それをoffマップにかけてからcreate_equivalent_widthにつなぐのが良いと思います。

> 他のfitsでも試してみようと思っていますが、MANGAの中で既に等価幅マップの結果がわかっているような例があると正当性を検証しやすいと思います。そのようなものはありますでしょうか？(例えば、ある論文で、あるfitsのこの吸収線領域における等価幅マップ結果が載っている、のようなもの)

これは明日以降に回答します。

**Comment by kazuyakusastro** [comment]
> Hαの場合の適切な範囲は後日お知らせします。

on-band: 3201-3215 pixel (6822-6836 A)
off-band1: 3147-3161 pixel (6768-6782 A)
off-band2: 3247-3261 pixel (6868-6882 A)
で試していただけるでしょうか。
銀河中心付近でEW(Hα) = -140 Aくらいになると思います。

> 他のfitsでも試してみようと思っていますが、MANGAの中で既に等価幅マップの結果がわかっているような例があると正当性を検証しやすいと思います。そのようなものはありますでしょうか？(例えば、ある論文で、あるfitsのこの吸収線領域における等価幅マップ結果が載っている、のようなもの)

下記論文のFigure 2. (e)と(f)が等価幅マップです。(Hαと[OIII]5007)
Chen et al. (2017), Astrophysical Journal Letters, 849, L4
https://ui.adsabs.harvard.edu//#abs/2017ApJ...849L...4C/abstract
このように論文に等価幅マップが載っている例は非常に少ないです。
大量の天体データを機械的に解析して、統計的性質を調べる論文がほとんどです。

MaNGAデータは以下です。
https://data.sdss.org/sas/dr14/manga/spectro/redux/v2_1_2/8454/stack/manga-8454-12703-LINCUBE.fits.gz

**Comment by dabokun** [comment]
ありがとうございます。off-bandについてですが、下限値を設定できるようにし、それ未満の値はNANになるようにしてみました。(create-equivalent_widthの一番下のスロットにつながる値がそれです。)

まず、いつものfitsでHαについての等価幅マップを計算したものを以下に示します。
おっしゃる通り、銀河中心付近では-180～-140Å程度になりました。
![image](https://user-images.githubusercontent.com/37533832/46780501-046f0180-cd58-11e8-85cb-568aa690e97e.png)

**Comment by kazuyakusastro** [comment]
ありがとうございます。
計算は概ね合っているように思います。
論文の図はカラースケールが対数 (log scale) になっていますので、ご注意ください。

論文の図に対して上下方向に反転して見えるとのことですが、on-bandの波長範囲を2-3 pixelずつ広げてみたらどうなるでしょうか？
この銀河はface-onに見えるけれど、図の上下方向で速度差が200 km/shほどあって (Figure 1参照)、on-bandに輝線が入っていないのかも知れません。

**Comment by dabokun** [comment]
対数スケールなのは失念していましたありがとうございます。

反転しているのはaflak側で画像を生成する際の処理の違いだと思います。現在論文のものを時計回りに90度回転したような生成方法になっている(上下反転していたのは自分のミスでしたが)ので、今はそれに合わせてあります。
![image](https://user-images.githubusercontent.com/37533832/46852207-28544500-ce35-11e8-9ba2-f59c35b26803.png)

**Comment by malikolivier** [comment]
@kazuyakusastro 結構進みましたので、報告します。
今からpushする最新版のaflakを実行すれば、上記のような図は作れます。

最新版をpullして、下記のコメンドでequivalent_widthが出来上がったノードエディターを確認していただけないでしょうか？

```sh
cargo run --release -- -f <FITS FILE> -t equivalent_width
# コマンドで迷った場合はhelpを使ってみてください。
cargo run --release -- --help
```

現状についてご意見を頂けないでしょうか？

**Comment by kazuyakusastro** [comment]
ありがとうございます。全体の流れはこれで良いと思います。

この例ではon-bandとoff-bandの波長範囲 (z pixel数) が全て同じになっていますが、これらは全てばらばらであるのが一般的です。
それを踏まえると、on-bandやoff-bandの画像を作るnodeはintegral (sum) よりaverageの方が後の処理が楽になると思います。

linear_composition_2dで、off1とoff2の寄与がどちらも0.5となっていますが、これは適切ではありません。
中心波長で考えて、それぞれの寄与を内分して (internal division) 決めると良いと思います。
これらの寄与をユーザーが手計算すると大変なので、on-bandやoff-bandの中心波長をintegralからoutputしてlinear_composition_2dにつなぎ、自動で計算してもらえると助かります。

ちょっと細かいですが、integralのパラメータを書き換えている途中で、a > b になるとすぐにaflak全体が落ちてしまうので困りました。

ひとまず以上です。
よろしくお願いします。

**Comment by malikolivier** [comment]
> ちょっと細かいですが、integralのパラメータを書き換えている途中で、a > b になるとすぐにaflak全体が落ちてしまうので困りました。

いいえ。正しい指摘です。今、修正しました。アップデートしたら、a >= bのinputでもaflakが落ちず、アウトプットのところに算出不能というエラーメッセージがちゃんと表示されます。 修正コミット: 2c975c9

> それを踏まえると、on-bandやoff-bandの画像を作るnodeはintegral (sum) よりaverageの方が後の処理が楽になると思います。

そうですね。averageも実装しましょう。 @dabokun integralと同じ感じでaverageを実装できますか？

> この例ではon-bandとoff-bandの波長範囲 (z pixel数) が全て同じになっていますが、これらは全てばらばらであるのが一般的です。
>
> linear_composition_2dで、off1とoff2の寄与がどちらも0.5となっていますが、これは適切ではありません。

適切な例を作ることができますでしょうか？作れば export ボタンをクリックして、exportした`editor_graph_export.ron`というファイルを送っていただけないですか。

> これらの寄与をユーザーが手計算すると大変なので、on-bandやoff-bandの中心波長をintegralからoutputしてlinear_composition_2dにつなぎ、自動で計算してもらえると助かります。

そうですね。中心波長というのは (a + b) / 2 のままですか？

**Comment by dabokun** [comment]
> そうですね。averageも実装しましょう。 @dabokun integralと同じ感じでaverageを実装できますか？

その部分だけですが実装しました↓
https://github.com/aflak-vis/aflak/pull/9

integral(average)から中心波長を流すとなると、outputが複数必要ということになるか、あるいは1つのoutputにこれらのデータも乗せることになりそうですが、どちらが良いか考える必要がありそうですね。

**Comment by kazuyakusastro** [comment]
> 適切な例を作ることができますでしょうか？作れば export ボタンをクリックして、exportしたeditor_graph_export.ronというファイルを送っていただけないですか。

作りましたので、お送りします。
averageをすでに実装してもらったということで、averageを使ったものになります。
ファイルを共有する方法がすぐに分からなくて、.ronファイルを.gzに圧縮しました。 (きっとよくない方法なのですが…。)

[editor_graph_export.ron.gz](https://github.com/aflak-vis/aflak/files/2570360/editor_graph_export.ron.gz)

> そうですね。中心波長というのは (a + b) / 2 のままですか？

そうです。

> 適切な例を作ることができますでしょうか？

上記の.ronファイルに適切な例を入れました。
今回のケースでは、on-bandとoff (1と2) の中心波長 (z pixel) がそれぞれ3144、3109、3184となります。
onに対するoff1とoff2の距離は35と40であり、よってoff1とoff2の寄与は40:35 = 0.533 : 0.467となります。

> integral(average)から中心波長を流すとなると、outputが複数必要ということになるか、あるいは1つのoutputにこれらのデータも乗せることになりそうですが、どちらが良いか考える必要がありそうですね。

そうですね、難しいところだと思います。
integral/averageからImage2dとfloatの2つをoutputにする方が、aflak全体を考えるとシンプルで良いかと思います。
linear_composition_2dやcreate_equivalent_widthにつなぐ時に毎回2本ずつ繋ぐ必要があって時間がかかりますが、許容範囲かと思います。

**Comment by malikolivier** [comment]
> ファイルを共有する方法がすぐに分からなくて、.ronファイルを.gzに圧縮しました。 (きっとよくない方法なのですが…。)

今はそういう方法しかないですね(*^^*)。私の期待のままです。ありがとうございます。この例をaflakに搭載させて頂きます。

> integral/averageからImage2dとfloatの2つをoutputにする方が、aflak全体を考えるとシンプルで良いかと思います。

では、その方向で進みますね。
実装が済んだら、@kazuyakusastro の作って頂いた例にも反映して頂いてもいいですか？

**Comment by malikolivier** [comment]
@kazuyakusastro 下記のような感じでいかがですか？ (a + b) / 2 を算出するアウトプットを追加しました。

![image](https://user-images.githubusercontent.com/14120117/48340235-18986e00-e638-11e8-8a91-06ec24e4e87a.png)

**Comment by kazuyakusastro** [comment]
integral/averageのoutput(float)の追加はこれで良いと思います。
linear_composition_2dで足し合わせる割合を計算する時には、off1とoff2の中心波長だけでなく、onの中心波長も必要であることに気が付きました。
割合の計算はlinear_composition_2d内で行うより、割合を計算するnodeを新たに作って、linear_composition_2dにつなぐのが良いと思います。
linear_composition_2dは等価幅の計算だけでなく、他の例でも使える汎用性の高いnodeだからです。

**Comment by malikolivier** [comment]
> 割合の計算はlinear_composition_2d内で行うより、割合を計算するnodeを新たに作って、linear_composition_2dにつなぐのが良いと思います。

@kazuyakusastro 阿呆な質問だと思いますが、おっしゃる「割合」はどのように計算されますか？

**Comment by dabokun** [comment]
> on、off1、off2の中心波長をz、z1、z2とすると、
(off1の割合) = (z - z1) / (z2 - z1)
(off2の割合) = (z2 - z) / (z2 - z1) = 1 - (off1の割合)
となります。

![image](https://user-images.githubusercontent.com/37533832/48463262-d67d5100-e81e-11e8-9b35-716c15fd23a8.png)

割合計算のノードを作ってみました。(ratio_from_bands)
寄与の比が距離の比を逆転させたものになるので、この式のままだと割合が逆転すると思いますが、ratio_from_bandsからの出力時に既に逆転したものであったほうが望ましいですか？

**Comment by kazuyakusastro** [comment]
出力時にすでに逆転していた方が良いです。
この例ではoutput #8が0.53333、#9が0.46666が望ましいです。
linear_composition_2dにつなぐ時に、上が上、下が下と揃って分かりやすいためです。

**Comment by malikolivier** [comment]
@kazuyakusastro @dabokunがratio_from_bandsを 51400bb で追加しました。

何か、このissueのユースケースを更に改善できる方向性があると思いますか？ご要望を聞かせてください。
このissueに関して特に改善するところがなければ、別の天文学の問題に重心を移そうかと思っています。

本issueと関係ないですが、ノードの数が増えて来ていますので、これからノードのカテゴリ機能を作って、UIから探しやすくするようにしようかと思っています。 その件に関して別issueを作りました： #12

**Comment by kazuyakusastro** [comment]
ありがとうございます。
ratio_from_bandsをつないで、前処理のaverageのInt valueを変えると、create_equivalent_widthの後でoutputされる画像が変わることを確認しました。

等価幅作成に関わる細かい改善点は以下になります。
・入力nodeのaverageの波長範囲を、スペクトルに引いたvertical lineにつなぎたいのですが、averageのinputはint、スペクトルvertical lineのoutputはfloatのためつなげません。
  averageのinputはfloatでもいいのかと思うのですが、どうでしょうか。
  intとfloatの変換nodeを作るか、自動的に変換するようにしてもいいと思います。

・linear_composition_2dのinput floatを何かのnodeからつないでinputした場合、枠内の数字がupdateされる方が分かりやすいと思いました。

・create_equivalent_widthの1つ目のfloatは、on-bandのintegral/average nodeの波長幅 (b - a) としたいです。
  integral/averageのoutputにb - aのoutputも付けてもらえますか？

**Comment by malikolivier** [comment]
> averageのinputはfloatでもいいのかと思うのですが、どうでしょうか。
> intとfloatの変換nodeを作るか、自動的に変換するようにしてもいいと思います。

ですね。。。私もこういう問題が出てくるだろうと思っていました。。。
考えて見れば、Integerが必ず必要なところはありますでしょうかね？Integerという型をなくして、全てのNumberをFloatのみにするのがいかがですか？

> ・linear_composition_2dのinput floatを何かのnodeからつないでinputした場合、枠内の数字がupdateされる方が分かりやすいと思いました。

そうですね。私もそういうのがあれば便利かと思いました。実装方法を検討してみます。  → #13

> create_equivalent_widthの1つ目のfloatは、on-bandのintegral/average nodeの波長幅 (b - a) としたいです。integral/averageのoutputにb - aのoutputも付けてもらえますか？

@dabokun 対応をお願いしていい？


また、nodeとinput/outputが増えることによって、混乱しないように、Node箱にinput/outputに名前をつけようかと思います。

**Comment by dabokun** [comment]
![image](https://user-images.githubusercontent.com/37533832/48910241-c7e40900-eeb2-11e8-9607-c43482a9c361.png)

Constant-nodeにBool値を扱うノードを追加しました。等価幅を計算する時に輝線なのか暗線なのかを判断する必要があると思うので、これをcreate-equivalent-widthの入力に組み込んで輝線と暗線どちらでも等価幅の大きさを扱えるようにします。

**Comment by malikolivier** [comment]
@dabokun 最新のノードを使えるようにequivalent_widthのテンプレートを修正していただけないでしょうか？
特に、ratio_from_bands を使うやつです。現在、templateはexportのronファイルと同じデータ形式を使っています。

**Comment by dabokun** [comment]
> @dabokun 最新のノードを使えるようにequivalent_widthのテンプレートを修正していただけないでしょうか？
特に、ratio_from_bands を使うやつです。現在、templateはexportのronファイルと同じデータ形式を使っています。

log scaleに変換するノードも加えたほうがいいでしょうか？ @malikolivier @kazuyakusastro 

> aflakを見慣れていたので気が付きませんでしたが、IRAF/DS9で表示したデータはpixelがよく見え?>ます。

これは論文の画像と見比べている時に自分も思いました。

**Comment by malikolivier** [comment]
> aflakは画像を表示する際に画像をならす (smooth) 処理を入れているのでしょうか？
> 画像をならすと解像度の低下に繋がる場合があるので、無い方が良いかと思います。
> S/Nが悪くて、数pixelならさないと見えない場合もあるため、ならす処理をするnodeがあるとより良いです。

@kazuyakusastro  そうですね。smoothingしないようにしておきます。 #23

> log scaleに変換するノードも加えたほうがいいでしょうか？ 

私にはわかりません。  @kazuyakusastro いかがでしょうか？

**Comment by kazuyakusastro** [comment]
logscaleに変換するnodeはあったほうが良いと思います。
output nodeの前に挟む感じでしょうか。

**Comment by dabokun** [comment]
> logscaleに変換するnodeはあったほうが良いと思います。
output nodeの前に挟む感じでしょうか。

そうなりますね。以前と同じPRですが、そのように修正しました。#24

**Comment by dabokun** [comment]
@kazuyakusastro 
> このissueの波長設定で、等価幅マップをIRAFで作ったものをお送りします。
equivalent_width_iraf.tar.gz
on-average.fitsがon-band、off-average.fitsがoff-band、ha-ew.fitsが等価幅マップです。
とても良く合っているように見えます。

今この部分の評価をしようとしています。off-average.fitsとon-average.fitsはfvやaflakでも開けるのですが、ha-ew.fitsを開くことができません。
![image](https://user-images.githubusercontent.com/37533832/49139469-369ee780-f335-11e8-97f8-8be0b058aaec.png)

**Comment by dabokun** [comment]
上の投稿についてですが、自前でirafを入れて計算したらできましたので解決しました。お騒がせしました。
![image](https://user-images.githubusercontent.com/37533832/49142881-23901580-f33d-11e8-81da-a90c5d3bd12e.png)
aflakで作成したものと差分をとってみましたが、ほとんどのところで±1.0 (1E-17 erg/s/cm^2/Ang/spaxel)となりました。

**Comment by malikolivier** [comment]
@kazuyakusastro 精密な調査ありがとうございました。
このissueでまだ未対応なところはありますでしょうか？

なければ閉じますので、教えてください。

**Comment by kazuyakusastro** [comment]
これで十分かと思います。
ありがとうございました。
