### ISSUE TITLE
Zoom in/out of spectra on MacBook

### ISSUE THREAD

**Issue by makotouemura** [aflak-vis/aflak#52]
extract_wave から output されたスペクトルを zoom in/out するときに、MacBook だと操作が難しいです。
手元の環境は MacBook Pro 2016、OS は Mojave 10.14.2です。
パッドの上で、２本指で上下にスライドすると zoom in/out になるのですが、指の移動量に対して zoom in/out の反応が強すぎるようです。

**Comment by dabokun** [comment]
https://github.com/aflak-vis/aflak/issues/83 にまとめましたのでcloseします。
