### ISSUE TITLE
空間次元の値の表示方法

### ISSUE THREAD

**Issue by kazuyakusastro** [aflak-vis/aflak#53]
2次元画像のoutput nodeで、X軸とY軸がそれぞれ赤経 (Right ascension) と赤緯 (Declination) になっていますが、面分光データは視野が狭いためほとんど同じ値になっています。
例えば、manga-8454-12703だと、ほとんどの目盛りで赤経は154.77 degree、赤緯は46.45 degreeです。

そこで、視野中心または基準位置 (CRVAL1とCRVAL2) からの相対座標で表すのが良いと思います。
単位はどちらもarcsec (= 1/3600 degree) が良いです。
赤緯は上に行くほど大きくなるのが一般的です。 (北が上、東が左。)

**Comment by malikolivier** [comment]
Duplicate with #70. I close.
